/** @format */

import Head from 'next/head';
import React from 'react';
import { Box } from '@mui/system';
import Layout from './Layout';
import { Context } from '../ContextComp';
import { useState, useLayoutEffect, useRef } from 'react';
import { request, gql } from 'graphql-request';
import { useMediaQuery } from '@mui/material';
import { home_schema } from './globalComponents/globalTypes';

interface MainLayout_schema extends home_schema {
	type: string;
	children: JSX.Element;
}

const MainLayout = (props: MainLayout_schema) => {
	const {
		placesOutput,
		categoriesOutput,
		type,
		mostCommentedOutput,
	} = props;
	const [numberToLoad, setNumberToLoad] = useState(
		placesOutput.length
	);
	const [data, setData] = useState(placesOutput);
	const firstUpdate = useRef(true);
	const maxWidth900 = useMediaQuery('(max-width:900px)');
	const maxWidth600 = useMediaQuery('(max-width:600px)');

	useLayoutEffect(() => {
		if (firstUpdate.current) {
			if (type === 'all') {
				const url =
					'https://api-eu-central-1.hygraph.com/v2/cl10szcbx0rd401z04l0ldt9g/master';
				const start = async () => {
					const query = gql`
						query PlaceQuery($numberToLoad: Int!) {
							placesSConnection(
								first: $numberToLoad
								orderBy: createdAt_ASC
							) {
								edges {
									node {
										description
										id
										photo {
											url
										}
										placeName
										category
										createdAt
									}
								}
							}
						}
					`;

					const variables = { numberToLoad };

					const response = await request(url, query, variables);
					const endResult = response.placesSConnection.edges;
					setData(endResult);
				};
				start();
			}
		}
	}, [numberToLoad, type]);

	return (
		<Context.Provider
			value={{
				data,
				categoriesOutput,
				mostCommentedOutput,
				setNumberToLoad,
				type,
				maxWidth900,
				maxWidth600,
			}}>
			<Box sx={{ position: 'relative' }}>
				<Layout>
					<>
						<Head>
							<title>Cool Placs Nextjs blog</title>
							<meta
								name='description'
								content='Generated by create next app'
							/>
							<link rel='icon' href='/favicon.ico' />
						</Head>
						{props.children}
					</>
				</Layout>
			</Box>
		</Context.Provider>
	);
};

export default MainLayout;
